#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
icudt<ver>l.dat (ICU 共通データパッケージ) を C ソースに変換する。

従来は objcopy で .dat を直接 .o に埋め込んでいたが、objcopy は
出力フォーマット (pe / elf / mach-o) やアーキテクチャ、シンボルの
アンダースコア有無をターゲットごとに指定する必要があり、特に
GNU objcopy は mach-o を出力できないため macOS ビルドで破綻する。

このスクリプトは .dat の中身を「16 バイト境界に整列した、先頭=データ
先頭バイトの C 配列」として出力する。ICU 側 (common/udata.cpp) は
    extern "C" const DataHeader U_DATA_API icudt<ver>_dat;
として、このシンボルの先頭 (オフセット 0) をそのまま DataHeader として
読むため、シンボルは .dat の先頭バイトを指していなければならない
(= objcopy が作っていたものと同じ契約)。

genccode が C 出力で先頭に付ける `double bogus` は、データ先頭が
magic に一致しないようにする特殊経路 (OS400 等。ICU 側が 8 バイト
スキップして読む) 専用なので、ここでは付けない。

生成物の特徴:
  * シンボル名は --symbol (既定 icudt77_dat)。C リンケージ
    (このファイルは C としてコンパイルされる) なので、x86 の
    アンダースコア付与なども含めコンパイラが面倒を見る = 移植性が高い。
  * 16 バイト整列 (ICU の .balign 16 と同じ要件)。
  * 中身は十進数値の要素初期化子 (unsigned char 配列)。以前は八進
    エスケープの文字列リテラル連結だったが、x86 ホスト版 MSVC
    (Hostx86) は巨大な連結文字列リテラルでフロントエンドのヒープを
    使い切り C1060 (compiler is out of heap space) で死ぬ
    (最適化やデバッグ情報の有無に関係なく発生)。数値配列初期化子は
    MSVC の大規模配列向け高速パスに乗るため 32bit ホストでも通り、
    コンパイル時間も同等 (いずれも数秒)。
"""

import argparse
import gzip
import os
import sys

# 1 行あたりのデータバイト数 (可読性とファイルサイズのバランスのみ。
# コンパイラの制限とは無関係)
BYTES_PER_LINE = 32


def _read_dat(dat_path):
    """入力を読み込む。gzip (先頭マジック 1f 8b) は自動で解凍する。"""
    with open(dat_path, 'rb') as f:
        magic = f.read(2)
    if magic == b'\x1f\x8b':
        with gzip.open(dat_path, 'rb') as f:
            return f.read()
    with open(dat_path, 'rb') as f:
        return f.read()


def generate(dat_path, out_path, symbol):
    data = _read_dat(dat_path)
    size = len(data)

    # コメント中のソース名は圧縮有無で出力が変わらないよう .gz を除去
    src_name = os.path.basename(dat_path)
    if src_name.endswith('.gz'):
        src_name = src_name[:-3]

    # 生成物は ASCII のみ (MSVC の codepage 932 などで C4819 を出さないため)
    header = (
        '/* Auto-generated by gen_icudata_c.py from %s. DO NOT EDIT.\n'
        ' * Embeds the ICU common data package as a C array.\n'
        ' * The first byte of symbol "%s" is the start of the data\n'
        ' * (ICU common/udata.cpp reads it as a DataHeader at offset 0).\n'
        ' */\n'
        '\n'
        '#if defined(_MSC_VER)\n'
        '#  define ICU_DATA_ALIGN __declspec(align(16))\n'
        '#  define ICU_DATA_ALIGN_ATTR\n'
        '#elif defined(__GNUC__) || defined(__clang__)\n'
        '#  define ICU_DATA_ALIGN\n'
        '#  define ICU_DATA_ALIGN_ATTR __attribute__((aligned(16)))\n'
        '#else\n'
        '#  define ICU_DATA_ALIGN\n'
        '#  define ICU_DATA_ALIGN_ATTR\n'
        '#endif\n'
        '\n'
        '/* %d bytes */\n'
        'ICU_DATA_ALIGN const unsigned char %s[] ICU_DATA_ALIGN_ATTR = {\n'
        % (src_name, symbol, size, symbol)
    )

    with open(out_path, 'w', newline='\n') as fout:
        fout.write(header)

        if not data:
            # 空データでも有効な配列定義にする (サイズ 1 になるが未使用)
            fout.write('0\n')
        else:
            for off in range(0, size, BYTES_PER_LINE):
                chunk = data[off:off + BYTES_PER_LINE]
                fout.write(','.join(['%d' % b for b in chunk]))
                fout.write(',\n')

        fout.write('};\n')

    return size


def main(argv):
    ap = argparse.ArgumentParser(
        description='ICU .dat を C ソース (16 バイト整列配列) に変換する')
    ap.add_argument('--input', required=True,
                    help='入力 .dat または .dat.gz ファイル (gzip は自動解凍)')
    ap.add_argument('--output', required=True, help='出力 .c ファイル')
    ap.add_argument('--symbol', default='icudt77_dat',
                    help='生成するシンボル名 (既定: icudt77_dat)')
    args = ap.parse_args(argv)

    if not os.path.isfile(args.input):
        sys.stderr.write('error: input not found: %s\n' % args.input)
        return 1

    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    size = generate(args.input, args.output, args.symbol)
    sys.stderr.write('generated %s (symbol=%s, %d bytes)\n'
                     % (args.output, args.symbol, size))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
